# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    container_name: postgres-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db:
    driver: local
